# Importing Numpy:

In [2]:
import numpy as np

# NUMPY NOTES

## Creating a numpy array:

In [12]:
array = [1,2,3,4,5]
np_array = np.array(array)
np_array

array([1, 2, 3, 4, 5])

In [13]:
np.array([1,2,3,4,5,6,7])

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
matrixes = [[10,20,30],[40,50,60],[70,80,90]]
matrixes = np.array(matrixes)
matrixes

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

### Arange method:

In [31]:
nplist1 = np.arange(30)
nplist1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

Creates a numpy array from 0 to 29.

In [15]:
np_array2 = np.arange(0,10)
np_array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Creates a numpy array from 0 to 9.

In [16]:
np_array3 = np.arange(0,10,2)
np_array3

array([0, 2, 4, 6, 8])

Creates a numpy array from 0 to 9 but only takes one from every two numbers.

### Zeros method:

In [17]:
nparray4 = np.zeros(5)
nparray4

array([0., 0., 0., 0., 0.])

Creates a numpy array with 5 zeros.

In [18]:
nparray5 = np.zeros((2,2))
nparray5

array([[0., 0.],
       [0., 0.]])

Creates a numpy array with the form of (2,2) zeros.

### Ones method:

In [19]:
nparray6 = np.ones(5)
nparray6

array([1., 1., 1., 1., 1.])

Creates a numpy array with 5 ones.

In [20]:
nparray7 = np.ones((2,2))
nparray7

array([[1., 1.],
       [1., 1.]])

Creates a numpy array with the form of (2,2) ones.

### Linspace method:

In [21]:
nplist8 = np.linspace(0,10,20)
nplist8

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

It divides the 0-10 range into 20 equal parts.

### Eye method:

In [22]:
nplist9 = np.eye(3)
nplist9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

It creates a 3 by 3 np array. Diagnols are ones and the rest is zero.

## Random Methods:

### Rand method:

In [23]:
nplist10 = np.random.rand(4)
nplist10

array([0.18175097, 0.54173022, 0.73969075, 0.87772076])

Generates 4 positive random numbers. (between 0-1)

In [26]:
nplist12 = np.random.rand(2,2)
nplist12

array([[0.18174477, 0.80632937],
       [0.76524327, 0.85877641]])

Generates 4 positive random numbers and creates a 2 by 2 array. (between 0-1)

### Randn method:

In [24]:
nplist11 = np.random.randn(4)
nplist11

array([-1.33956333, -0.4311403 , -0.79801374, -0.83727745])

Generates 4 positive or negative random numbers. (between 0-1)

In [27]:
nplist13 = np.random.randn(2,2)
nplist13

array([[ 0.85901031,  0.50492608],
       [-1.2844253 ,  0.77436278]])

Generates 4 positive or negative random numbers and creates a 2 by 2 array. (between 0-1)

### Randint method:

In [28]:
nplist14 = np.random.randint(8)
nplist14

5

Generates random integer numbers from 0-8 (not including 8).

In [29]:
nplist15 = np.random.randint(0,17)
nplist15

14

Generates random integer numbers from 0-17 (not including 17).

In [30]:
nplist16 = np.random.randint(0,10,5)
nplist16

array([6, 4, 2, 1, 8])

Generates 5 random integer numbers from 0-10 (not including 10).

## Other Methods:

### Reshape method:

In [32]:
nplist17 = nplist1.reshape(5,6)
nplist17

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

Reshape changes the shape of the array. First parameter is row, second one is column.

### Comparing Methods:

### Min, Max methods:

In [33]:
max = nplist17.max()
min = nplist17.min()
max, min

(29, 0)

Max = Max number in the array.\
Min = Min number in the array.

### Argmax, Argmin methods:

In [34]:
argmax = nplist17.argmax()
argmin = nplist17.argmin()
argmax, argmin

(29, 0)

Argmax = It brings the index of the max number.\
Argmin = It brings the index of the min number.

## Numpy Operations:

In [35]:
result = nplist1[3]
result

3

It brings the number with the index of 3.

In [36]:
sliced_array = nplist1[3:8]
sliced_array

array([3, 4, 5, 6, 7])

It brings the number whose indexes are from 3 to 8.(except 8)

In [38]:
nplist16[3:8] = -5
nplist16

array([ 6,  4,  2, -5, -5])

It assignes the value -5 to the elements of the array at indexes 3-8. (except 8)

In [39]:
sliced_array[:] = 10
sliced_array

array([10, 10, 10, 10, 10])

We assigned the value 10 to the elements of the array.

In [40]:
new_array = nplist1.copy()
new_array

array([ 0,  1,  2, 10, 10, 10, 10, 10,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, -5, -5, -5, -5, -5, -5, -5, -5, -5, -5, -5, -5])

We copied the numpy array.

### Important! :

In [42]:
newarray = np.arange(0,30)
copiedArray = newarray.copy()
copiedArraySliced = copiedArray[3:8]
copiedArraySliced[:] = 10

copiedArraySliced

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
copiedArray

array([ 0,  1,  2, 10, 10, 10, 10, 10,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
newarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### Matrix operations:

In [45]:
matrixes

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [46]:
matrixes[0]

array([10, 20, 30])

In [47]:
matrixes[0][2]

30

In [48]:
matrixes[1,2]

60

matrixes[row, column]

In [50]:
result = matrixes[1:,2]
result

array([60, 90])

In [51]:
result = matrixes[2:,1:]
result

array([[80, 90]])

In [52]:
matrixes[[0,1,2]]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [53]:
matrixes[[0,1]]

array([[10, 20, 30],
       [40, 50, 60]])

### General Operations:

In [54]:
newestArray = np.random.randint(1,100,30)
newestArray

array([70, 80, 52, 59, 99, 46, 94, 54, 79, 52, 21, 82,  5, 26, 80, 67, 87,
       80, 19, 92, 14, 93, 89, 81, 60, 40, 13, 57, 65, 85])

In [55]:
isBig = newestArray > 50
isBig

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True, False, False,
        True,  True,  True])

Returns a boolean value for all the elements of the array.

In [56]:
newestArray[isBig]

array([70, 80, 52, 59, 99, 94, 54, 79, 52, 82, 80, 67, 87, 80, 92, 93, 89,
       81, 60, 57, 65, 85])

We can reach the values by doing this. Or this way: 

In [57]:
newestArray[newestArray > 50]

array([70, 80, 52, 59, 99, 94, 54, 79, 52, 82, 80, 67, 87, 80, 92, 93, 89,
       81, 60, 57, 65, 85])

In [58]:
sum_array = newestArray + newestArray
sum_array

array([140, 160, 104, 118, 198,  92, 188, 108, 158, 104,  42, 164,  10,
        52, 160, 134, 174, 160,  38, 184,  28, 186, 178, 162, 120,  80,
        26, 114, 130, 170])

We can sum numpy arrays.

In [60]:
multiplyed_array = newestArray * newestArray
multiplyed_array

array([4900, 6400, 2704, 3481, 9801, 2116, 8836, 2916, 6241, 2704,  441,
       6724,   25,  676, 6400, 4489, 7569, 6400,  361, 8464,  196, 8649,
       7921, 6561, 3600, 1600,  169, 3249, 4225, 7225])

We can multiply numpy arrays.

In [61]:
subtracked_array = newestArray - newestArray
subtracked_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

We can subtrack numpy arrays.

In [62]:
np.sqrt(newestArray)

array([8.36660027, 8.94427191, 7.21110255, 7.68114575, 9.94987437,
       6.78232998, 9.69535971, 7.34846923, 8.88819442, 7.21110255,
       4.58257569, 9.05538514, 2.23606798, 5.09901951, 8.94427191,
       8.18535277, 9.32737905, 8.94427191, 4.35889894, 9.59166305,
       3.74165739, 9.64365076, 9.43398113, 9.        , 7.74596669,
       6.32455532, 3.60555128, 7.54983444, 8.06225775, 9.21954446])

It brings the sqrt values of every element.